### PR TITLE
Add byte array read() methods to SerialInputStream

### PR DESCRIPTION
**Pull request by WestonP22**
Although the existing single byte read() method did get called when doing a byte array read(), it would block until the entire byte array was filled. If the byte array was larger than the data received, it would block indefinitely. This commit adds byte array read() method overrides that only block until data is available or EOF, consistent with other InputStream classes.

### CODE REVIEW

**Comment by felHR85** [comment]
Hi @WestonP22 
I will check it out a soon as possible.
Thanks!

**Comment by dani2584** [comment]
hi .
is it correct?
how can i added it to my project??

**Comment by WestonP22** [comment]
This change was necessary for the project I'm using it in, and it has worked great for me. I've also made a branch with my changes here: https://github.com/WestonP22/UsbSerial

**Comment by felHR85** [comment]
Already solved in Master by #169

**Pull request closed without merging**
