### PR TITLE
Fix null exception crash in read() API by checking nullability first.

### PR DESCRIPTION
**Pull request by quangctkm9207**

### CODE REVIEW

**Comment by Fyb3roptik** [comment]
Can we get this pull request merged please???

**Comment by quangctkm9207** [comment]
It seems that this project is not actively maintained. The last commit is from 1 year ago.

**Comment by eyedol** [comment]
Unfortunately, the author has been very quiet on this project. I have sent him an email to see if he's still interested in maintaining it. His GitHub activity has been scanty these past few years. I have asked him if he could add me as a maintainer, I'm happy to at least keep this project alive by doing code reviews and merging PR's from the community.

Let's hope life hasn't gotten in the way of him.

**Comment by felHR85** [comment]
Hello guys,
I am sorry but my time this last year has been very limited. I've added @eyedol as maintainer.
I will still keep an eye on the project.

**Comment by quangctkm9207** [comment]
Thank you @felHR85 and @eyedol. So happy that this great library is alive again. :D

**Pull request merged**
