### PR TITLE
Update readme.

### PR DESCRIPTION
**Pull request by StephaneBg**
Update readme for gradle integration of the project thanks to Jitpack.
Remove IDE files.

### CODE REVIEW

**Comment by felHR85** [comment]
Hi @StephaneBg 
I didn't know about jitpack so thank you very much for this addition. Could be used right now with this pull request accepted calling compile 'com.github.felHR85:UsbSerial:v3.2' ?

**Comment by StephaneBg** [comment]
I've found a problem with the current latest release. So it can't be used right now. You'll have to perform a new release (3.3 I guess).
The problem is a not required dependency included in the current version. I removed this dependency in my last PR.

**Comment by felHR85** [comment]
I'll add a new release.
Thanks!

**Comment by felHR85** [comment]
3.3 release appears to be working!

**Comment by StephaneBg** [comment]
Yes, it tried it also.
Do you consider to include example module in the same repository than the
library?

Le sam. 9 janv. 2016 à 15:10, Felipe Herranz <notifications@github.com> a
écrit :

**Comment by felHR85** [comment]
If it doesn't add a lot of overhead(it shouldn't) it is ok to me

**Comment by BenLeggieroNCR** [comment]
Is there an incentive for 3.2 users to update the 3.3 JAR?

**Comment by StephaneBg** [comment]
None except that JAR is no more needed.

**Comment by BenLeggieroNCR** [comment]
@StephaneBg what do you mean? We don't want to put a full project into our own and compile that every time; we'd much rather use a precompiled executable. This is our approach for all other 3rd-party libraries we use.

**Comment by felHR85** [comment]
@BenLeggieroNCR He doesnt mean that. Check the readme, there are changes (Gradle)

**Comment by BenLeggieroNCR** [comment]
@felHR85 so I'll have to add more dependencies if/when I ever want to update our JAR?

**Comment by StephaneBg** [comment]
@BenLeggieroNCR Not at all! You should switch to gradle build system that eases dependencies.

**Comment by BenLeggieroNCR** [comment]
@StephaneBg we use gradle already. I'm very confused about all this. Simply answer my questions, please:

1. Should I update the JAR because of this change?
2. When I eventually update the JAR, do I have to change my build.gradle files?
3. If I have to change the build.gradle files, what kind of changes would I have to make?

**Comment by felHR85** [comment]
@BenLeggieroNCR There's nothing to be worried!
1) Delete the UsbSerial.jar , there is no need for it anymore. Go to the project /build.gradle and add this
```groovy
allprojects {
	repositories {
		jcenter()
		maven { url "https://jitpack.io" }
	}
}
```
And this into the module gradle
```groovy
compile 'com.github.felHR85:UsbSerial:3.3'
```
This will add UsbSerial as dependency automatically without more worries.

2) Maybe jitpack can add the lastest version using something like 
```groovy
compile 'com.github.felHR85:UsbSerial:*'
```
but I guess @StephaneBg can give us more information. In the worst case Scenario if I release a 3.4 version just update that line 
```groovy
compile 'com.github.felHR85:UsbSerial:3.4'
```

**Comment by BenLeggieroNCR** [comment]
@felHR85 

1. So you want me to remove my local JAR and replace it with one that's fetched every time we build? This is _not_ without worries.
  1. Does that mean that our build server needs an internet connection to build this?
  2. What if jitpack.io goes down, or you remove your library from there?
  3. What if a [man-in-the-middle](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) replaces your library with a malicious one? Or if some black-hat hacker replaces your library on jitpack.io with a malicious one? I don't see any checksum validation, here, and I need that to guarantee I'm getting what I think I am getting.

**Comment by felHR85** [comment]
[Add the aar manually](http://stackoverflow.com/questions/24506648/adding-local-aar-files-to-gradle-build-using-flatdirs-is-not-working)

**Comment by felHR85** [comment]
[JitPack FAQ with information about its security](https://jitpack.io/docs/FAQ/)

**Pull request merged**
